server:
  port: 8202



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leo-springboot-tutorial?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: gzm2001..  #数据库名、用户名和密码改为自己的
    driver-class-name: com.mysql.cj.jdbc.Driver
