server:
  port: 8008



# 对象存储服务配置
file:
  # MinIO自搭建对象存储服务
  minio:
    endpoint: http://localhost:9000 #存储服务域名
    accessKey: your-access-key #AccessKey
    secretKey: your-secret-key #SecretKey
    bucket: your-bucket-name   #存储桶名称